images:
  image:
    repository: fnsys/dockhand
    tag: v1.0.6
  container_utils_image:
    repository: ixsystems/container-utils
    tag: 1.0.2

consts:
  dockhand_container_name: dockhand
  perms_container_name: permissions
  notes_body: |
    On first launch, authentication is disabled.
    Go to Settings > Authentication to enable authentication.
